wip: v22.14.0+solaris
error due to old gcc??

```
2025-03-02T10:30:50.5073212Z   g++ -o /home/runner/work/node/node/out/Release/obj.target/v8_compiler/deps/v8/src/compiler/wasm-compiler.o ../deps/v8/src/compiler/wasm-compiler.cc '-D_GLIBCXX_USE_CXX11_ABI=1' '-DNODE_OPENSSL_CONF_NAME=nodejs_conf' '-DNODE_OPENSSL_HAS_QUIC' '-DICU_NO_USER_DATA_OVERRIDE' '-DV8_GYP_BUILD' '-DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DV8_TARGET_ARCH_X64' '-D__C99FEATURES__=1' '-DV8_EMBEDDER_STRING="-node.22"' '-DENABLE_DISASSEMBLER' '-DV8_PROMISE_INTERNAL_FIELD_COUNT=1' '-DV8_SHORT_BUILTIN_CALLS' '-DOBJECT_PRINT' '-DV8_INTL_SUPPORT' '-DV8_ATOMIC_OBJECT_FIELD_WRITES' '-DV8_ENABLE_LAZY_SOURCE_POSITIONS' '-DV8_USE_SIPHASH' '-DV8_SHARED_RO_HEAP' '-DNDEBUG' '-DV8_WIN64_UNWINDING_INFO' '-DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH' '-DV8_USE_ZLIB' '-DV8_ENABLE_SPARKPLUG' '-DV8_ENABLE_TURBOFAN' '-DV8_ENABLE_WEBASSEMBLY' '-DV8_ENABLE_JAVASCRIPT_PROMISE_HOOKS' '-DV8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA' '-DV8_ALLOCATION_FOLDING' '-DV8_ALLOCATION_SITE_TRACKING' '-DV8_ADVANCED_BIGINT_ALGORITHMS' '-DV8_ENABLE_WASM_SIMD256_REVEC' '-DUCONFIG_NO_SERVICE=1' '-DU_ENABLE_DYLOAD=0' '-DU_STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=1' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/v8 -I../deps/v8/include -I/home/runner/work/node/node/out/Release/obj/gen/generate-bytecode-output-root -I/home/runner/work/node/node/out/Release/obj/gen -I../deps/icu-small/source/i18n -I../deps/icu-small/source/common -I../deps/v8/third_party/abseil-cpp  -Wno-unused-parameter -pthreads -Wno-strict-overflow -Wno-return-type -Wno-int-in-bool-context -Wno-deprecated -Wno-stringop-overflow -Wno-stringop-overread -Wno-restrict -Wno-array-bounds -Wno-nonnull -Wno-dangling-pointer -flax-vector-conversions -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -fno-strict-aliasing -std=gnu++20 -Wno-invalid-offsetof -MMD -MF /home/runner/work/node/node/out/Release/.deps//home/runner/work/node/node/out/Release/obj.target/v8_compiler/deps/v8/src/compiler/wasm-compiler.o.d.raw   -c
2025-03-02T10:31:08.5256889Z ../deps/v8/src/compiler/wasm-compiler.cc: In lambda function:
2025-03-02T10:31:08.5259051Z ../deps/v8/src/compiler/wasm-compiler.cc:8620:59: error: too many initializers for ‘v8::internal::wasm::WrapperCompilationInfo::<unnamed union>’
2025-03-02T10:31:08.5259866Z  8620 |             .import_info = {kind, expected_arity, suspend}},
2025-03-02T10:31:08.5260255Z       |                                                           ^
2025-03-02T10:31:08.5272631Z ../deps/v8/src/compiler/wasm-compiler.cc: In function ‘v8::internal::wasm::WasmCompilationResult v8::internal::compiler::CompileWasmImportCallWrapper(v8::internal::wasm::CompilationEnv*, v8::internal::wasm::ImportCallKind, const FunctionSig*, bool, int, v8::internal::wasm::Suspend)’:
2025-03-02T10:31:08.5275058Z ../deps/v8/src/compiler/wasm-compiler.cc:8658:76: error: use of ‘v8::internal::compiler::CompileWasmImportCallWrapper(v8::internal::wasm::CompilationEnv*, v8::internal::wasm::ImportCallKind, const FunctionSig*, bool, int, v8::internal::wasm::Suspend)::<lambda()>’ before deduction of ‘auto’
2025-03-02T10:31:08.5276232Z  8658 |   auto result = v8_flags.turboshaft_wasm_wrappers ? compile_with_turboshaft()
2025-03-02T10:31:08.5276631Z       |                                                     ~~~~~~~~~~~~~~~~~~~~~~~^~
2025-03-02T10:31:08.5572192Z ../deps/v8/src/compiler/wasm-compiler.cc: In lambda function:
2025-03-02T10:31:08.5573681Z ../deps/v8/src/compiler/wasm-compiler.cc:8782:63: error: too many initializers for ‘v8::internal::wasm::WrapperCompilationInfo::<unnamed union>’
2025-03-02T10:31:08.5574681Z  8782 |                 .import_info = {kind, expected_arity, suspend}},
2025-03-02T10:31:08.5575405Z       |                                                               ^
2025-03-02T10:31:12.2705085Z At global scope:
2025-03-02T10:31:12.2716668Z cc1plus: note: unrecognized command-line option ‘-Wno-dangling-pointer’ may have been intended to silence earlier diagnostics
2025-03-02T10:31:12.5322906Z gmake[1]: *** [tools/v8_gypfiles/v8_compiler.target.mk:329: /home/runner/work/node/node/out/Release/obj.target/v8_compiler/deps/v8/src/compiler/wasm-compiler.o] Error 1
2025-03-02T10:31:12.5336893Z rm 9ac559b3661ef3e3ae7143f36ccc6691e578b31c.intermediate 2ad06b2c9baade6b27c5c82cdcc7af11c369378d.intermediate 02a486ff0aa87df511c38b125409357fdc559df2.intermediate
2025-03-02T10:31:12.5424902Z gmake: *** [Makefile:135: node] Error 2
```